# Generated by Django 6.1.1 on 2026-09-24 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='EduSphere University', max_length=150)),
                ('academic_year', models.CharField(default='2026', max_length=20)),
                ('default_semester', models.CharField(default='8th Semester', max_length=50)),
                ('recent_students_count', models.PositiveIntegerField(default=5)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('academic_alerts', models.BooleanField(default=True)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
